name: 生成 Changelog 并发布版本

on:
  workflow_call:
    inputs:
      runid:
        required: true
        type: string

jobs:
  generate-changelog-and-release:
    name: 生成 Changelog 并发布版本
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get previous tag
        uses: younited/get-previous-tag-action@v1.0.0
        id: getprevtag
      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v1
      - name: Generate a changelog
        id: generate-changelog
        run: |
          git cliff
      - name: Prepare release
        run: mkdir release
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          run-id: ${{ github.event.workflow_run.id }}
      - name: Clean
        run: rm "*single).zip"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          body_path: CHANGELOG.md
          draft: true
